name: Continuous integration
on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - build_stable

jobs:
  run-game:
    name: run client and server
    runs-on: windows-2022
    timeout-minutes: 15
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache files
        id: cache-app
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\asrd
          key: cache-app

      - name: Cleanup
        run: |
          ./cleanup-steamcmd.ps1  ${{ github.workspace }}\asrd

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Download the game
        run: steamcmd +force_install_dir ${{ github.workspace }}\asrd +logon anonymous +app_update 563560 -beta beta +app_update 1007 +quit

      - name: Run the client
        run: |
          cd ${{ github.workspace }}\asrd
          echo "cvarlist log cvars-client.txt; quit" > reactivedrop/cfg/test.cfg
          cmd /c start /wait reactivedrop.exe -textmode -condebug -conclearlog +exec test
          mv -Force ${{ github.workspace }}/asrd/reactivedrop/console.log ${{ github.workspace }}/asrd/console-client.log

      - name: Run the server
        run: |
          cd ${{ github.workspace }}\asrd
          echo "cvarlist log cvars-server.txt; map lobby; quit" > reactivedrop/cfg/servertest.cfg
          cmd /c start /wait srcds_console.exe -console -condebug -conclearlog -game reactivedrop -noassert +sv_lan 1 +exec servertest
          mv -Force ${{ github.workspace }}/asrd/reactivedrop/console.log ${{ github.workspace }}/asrd/console-server.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rd-artifacts
          path: |
            ${{ github.workspace }}/asrd/reactivedrop/cvars-client.txt
            ${{ github.workspace }}/asrd/reactivedrop/cvars-server.txt
            ${{ github.workspace }}/asrd/console-client.log
            C:\hostedtoolcache\windows\steamcmd\latest\i386\depotcache\*

  dispatch-anticheat:
    name: dispatch anticheat build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: run-game
    timeout-minutes: 5
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/reactive-drop-anticheat
          token: ${{ secrets.CR_PAT }}
          event-type: build_stable

  generate-files:
    name: generate additional files
    runs-on: ubuntu-latest
    needs: run-game
    timeout-minutes: 5
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rd-artifacts
          path: asrd

      - name: List artifacts
        run: |
          find . -type f

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Generate convarlist
        run: |
          php generate-convarlist > convarlist.wiki.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rd-convarlist-wiki
          path: convarlist.wiki.txt



