name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types:
      - build_stable
  workflow_dispatch: {}

jobs:

  run-game:
    name: run client and server
    runs-on: windows-2022
    timeout-minutes: 30
    steps:
      - name: Checkout project
        uses: actions/checkout@v7

      - name: Cache files
        id: cache-app
        uses: actions/cache@v6
        with:
          path: ${{ github.workspace }}\asrd
          key: cache-app

      - name: Cleanup
        run: |
          ./cleanup-steamcmd.ps1  ${{ github.workspace }}\asrd

        ##################
        # setup workflow #
        ##################

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Download the game
        run: |
          steamcmd +force_install_dir ${{ github.workspace }}\asrd `
            +logon anonymous +app_update 563560 +app_update 1007 +beta beta +quit

      - name: Create log folders
        working-directory: ${{ github.workspace }}\asrd
        run: |
          New-Item -ItemType Directory -Force -Path map-logs | Out-Null

        ############################
        # run and export cvarlist  #
        ############################

      - name: Run the client (cvarlist, cvarlist_rd)
        working-directory: ${{ github.workspace }}\asrd
        run: |
          echo "::group::-- cvarlist client --"   
          echo "cvarlist log cvars-client.txt; quit" > reactivedrop/cfg/test.cfg
          ../run-client.ps1 map-logs/cvarlist.client.log
          echo "::endgroup::"

          echo "::group::-- cvarlist_rd client --"   
          echo "cvarlist_rd 3; quit" > reactivedrop/cfg/test.cfg
          ../run-client.ps1 map-logs/cvarlist-rd.client.log
          echo "::endgroup::"

          echo "::group::-- cvarlist_rd conversion --"
          cd map-logs
          findstr /b "\""" cvarlist-rd.client.log `
            > ../reactivedrop/cvars-client-new.txt
          echo "::endgroup::"

      - name: Run the server (cvarlist)
        working-directory: ${{ github.workspace }}\asrd
        run: |
          echo "cvarlist log cvars-server.txt; map lobby; quit" > reactivedrop/cfg/test.cfg
          ../run-server.ps1 map-logs/cvarlist.server.log

      #########################################################
      # run map specific tests and see if they load correctly #
      #########################################################
      - name: Run map tests
        working-directory: ${{ github.workspace }}\asrd
        run: |
          $maps = Get-ChildItem reactivedrop/maps -Filter *.bsp
          $mapList = $maps | ForEach-Object { $_.Name.replace(".bsp", "") }

          $mapsList | ForEach-Object {
            echo "::group::-- Testing map: $_ (server) --"   
            echo "map $_; quit" > reactivedrop/cfg/test.cfg
            ../run-server.ps1 map-logs/map-$_.server.log
            echo "::endgroup::"

            echo "::group::-- Testing map: $_ (client) --"   
            echo "map $_; quit" > reactivedrop/cfg/test.cfg
            ../run-client.ps1 map-logs/map-$_.client.log
            echo "::endgroup::"
          }
          
          Write-Host "testing finished!"

        ###################
        # store some data #
        ###################

      - name: Store manifest
        run: |
          cp -Force -Recurse C:\hostedtoolcache\windows\steamcmd\latest\i386\depotcache `
            ${{ github.workspace }}/asrd/depotcache

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: rd-artifacts
          path: |
            ${{ github.workspace }}/asrd/reactivedrop/cvars-client-new.txt
            ${{ github.workspace }}/asrd/reactivedrop/cvars-client.txt
            ${{ github.workspace }}/asrd/reactivedrop/cvars-server.txt
            ${{ github.workspace }}/asrd/depotcache
            ${{ github.workspace }}/asrd/map-logs

  dispatch-anticheat:
    name: dispatch depending repositories
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: run-game
    timeout-minutes: 5
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          repository: ${{ github.repository_owner }}/reactive-drop-anticheat
          token: ${{ secrets.CR_PAT }}
          event-type: build_stable

  generate-files:
    name: generate additional files
    runs-on: ubuntu-latest
    needs: run-game
    timeout-minutes: 5
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: rd-artifacts
          path: asrd

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Generate convarlist
        run: |
          php generate-convarlist > convarlist.wiki.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: rd-convarlist-wiki
          path: convarlist.wiki.txt




