name: Continuous integration
on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - build_stable

jobs:
  get-depots:
    name: download steam depot
    runs-on: windows-2022
    timeout-minutes: 5
    steps:
      - name: Download steam depot downloader
        run: |
          curl -L -o downloader.zip https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_3.4.0/DepotDownloader-windows-x64.zip
          tar -xf downloader.zip
      - name: Download depot manifest
        run: |
          ./DepotDownloader.exe -app 563560 -depot 563561 -manifest-only -beta beta
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rd-depots
          path: |
            depots

  generate-convarlist:
    name: run client and server
    runs-on: windows-2022
    timeout-minutes: 15
    needs: get-depots
    steps:
      - name: Cache files
        id: cache-app
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\asrd
          key: cache-app

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Download the game
        run: steamcmd +force_install_dir ${{ github.workspace }}\asrd +logon anonymous +app_update 563560 +app_update 1007 +quit
      - name: Run the client
        run: |
          cd ${{ github.workspace }}\asrd
          echo "cvarlist log cvars-client.txt; quit" > reactivedrop/cfg/test.cfg
          cmd /c start /wait reactivedrop.exe -textmode -condebug -conclearlog +exec test
          mv ${{ github.workspace }}/asrd/reactivedrop/console.log ${{ github.workspace }}/asrd/console-client.log
      - name: Run the server
        run: |
          cd ${{ github.workspace }}\asrd
          echo "cvarlist log cvars-server.txt; quit" > reactivedrop/cfg/servertest.cfg
          cmd /c start /wait srcds_console.exe -console -condebug -conclearlog -game reactivedrop -noassert +sv_lan 1 +exec servertest +map lobby
          mv ${{ github.workspace }}/asrd/reactivedrop/console.log ${{ github.workspace }}/asrd/console-server.log
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rd-convar-list
          path: |
            ${{ github.workspace }}/asrd/reactivedrop/cvars-client.txt
            ${{ github.workspace }}/asrd/reactivedrop/cvars-server.txt
            ${{ github.workspace }}/asrd/console-client.log
            ${{ github.workspace }}/asrd/console-server.log

